schema_version: 1

context:
  name: azure-mgmt-postgresqlflexibleservers
  version: 1.1.0b2

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/azure_mgmt_postgresqlflexibleservers-${{ version }}.tar.gz
  sha256: f0eb026f275f97bf95ae82cd58e30a760fff2944a7f4a80fc285aaf8da070934

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - setuptools
    - python ${{ python_min }}.*
    - pip
  run:
    - python >=${{ python_min }}
    - azure-common >=1.1
    - azure-mgmt-core >=1.3.2
    - isodate >=0.6.1
    - typing-extensions >=4.6.0

tests:
  - python:
      imports:
        - azure.mgmt.postgresqlflexibleservers
        - azure.mgmt.postgresqlflexibleservers.aio
      pip_check: true
      python_version: ${{ python_min }}.*
about:
  summary: Microsoft Azure Postgresqlflexibleservers Management Client Library for Python
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/Azure/azure-sdk-for-python

extra:
  recipe-maintainers:
    - janjagusch
